[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 10000
libs = ["lib"]


# Remappings for imported libraries
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
    "@prb-math/=lib/prb-math/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
